# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manlog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
from PyQt5.uic import loadUi

class Ui_MainWindow(QDialog):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 140, 871, 108))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        
#Individual controls
        self.interval = QtWidgets.QLabel(self.centralwidget)
        self.interval.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.interval.setObjectName("interval")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(20, 110, 141, 24))
        self.spinBox.setObjectName("interval_spinBox")
        
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(10, 40, 141, 32))
        self.openFileButton.setObjectName("Open_file")
        
        self.openFileButton.clicked.connect(self.browsefiles) #open file browser
        
        
#file saving
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(738, 40, 151, 94))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.File_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.File_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.File_grid_layout.setObjectName("File_grid_layout")
        self.filename = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.filename.setObjectName("filename")
        self.File_grid_layout.addWidget(self.filename, 2, 0, 1, 1)
        self.log = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.log.setObjectName("log")
        self.File_grid_layout.addWidget(self.log, 3, 0, 1, 1)
        self.file_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.file_name.setObjectName("file_name")
        self.File_grid_layout.addWidget(self.file_name, 1, 0, 1, 1)
        
#main section titles
        self.title_grid = QtWidgets.QGridLayout(self.gridLayoutWidget) 
        self.title_grid.setContentsMargins(0, 0, 0, 0)
        self.title_grid.setObjectName("title_grid")
        self.gridLayoutWidget.setStyleSheet("background-color:white;")
        self.do2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.do2.setObjectName("do2")
        self.title_grid.addWidget(self.do2, 2, 4, 1, 1)
        self.test = QtWidgets.QLabel(self.gridLayoutWidget)
        self.test.setObjectName("test")
        self.title_grid.addWidget(self.test, 0, 1, 1, 1)
        self.temperature = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temperature.setObjectName("temperature")
        self.title_grid.addWidget(self.temperature, 2, 1, 1, 1)
        self.pH = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pH.setObjectName("pH")
        self.title_grid.addWidget(self.pH, 2, 3, 1, 1)
        self.co2flow = QtWidgets.QLabel(self.gridLayoutWidget)
        self.co2flow.setObjectName("co2flow")
        self.title_grid.addWidget(self.co2flow, 2, 7, 1, 1)
        self.pressure = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pressure.setObjectName("pressure")
        self.title_grid.addWidget(self.pressure, 2, 2, 1, 1)
        self.date = QtWidgets.QLabel(self.gridLayoutWidget)
        self.date.setObjectName("date")
        self.title_grid.addWidget(self.date, 0, 0, 1, 1)
        self.motor = QtWidgets.QLabel(self.gridLayoutWidget)
        self.motor.setObjectName("motor")
        self.title_grid.addWidget(self.motor, 2, 8, 1, 1)
        self.o2flow = QtWidgets.QLabel(self.gridLayoutWidget)
        self.o2flow.setObjectName("o2flow")
        self.title_grid.addWidget(self.o2flow, 2, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_grid.addItem(spacerItem, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_grid.addItem(spacerItem1, 1, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_grid.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_grid.addItem(spacerItem3, 1, 5, 1, 1)
        self.group = QtWidgets.QLabel(self.gridLayoutWidget)
        self.group.setObjectName("group")
        self.title_grid.addWidget(self.group, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_grid.addItem(spacerItem4, 1, 8, 1, 1)
        self.datetime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.datetime.setObjectName("datetime")
        self.title_grid.addWidget(self.datetime, 2, 0, 1, 1)
        self.airflow = QtWidgets.QLabel(self.gridLayoutWidget)
        self.airflow.setObjectName("airflow")
        self.title_grid.addWidget(self.airflow, 2, 5, 1, 1)
        self.operator_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.operator_2.setObjectName("operator_2")
        self.title_grid.addWidget(self.operator_2, 0, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setMinimumSize(QtCore.QSize(141, 0))
        self.dateEdit.setObjectName("dateEdit")
        self.title_grid.addWidget(self.dateEdit, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(81, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(81, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.title_grid.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(81, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.title_grid.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(81, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.title_grid.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        
        #scroll area
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(18, 248, 875, 350))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 871, 470))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 871, 434))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setStyleSheet("background-color:white;")
        
        #text boxes
        self.lineEdit_27 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout.addWidget(self.lineEdit_27, 2, 3, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout.addWidget(self.lineEdit_28, 3, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 11, 1, 1, 1)
        self.lineEdit_83 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.gridLayout.addWidget(self.lineEdit_83, 10, 8, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout.addWidget(self.lineEdit_26, 1, 3, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout.addWidget(self.lineEdit_59, 7, 7, 1, 1)
        self.lineEdit_93 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.gridLayout.addWidget(self.lineEdit_93, 8, 2, 1, 1)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout.addWidget(self.lineEdit_64, 4, 8, 1, 1)
        self.lineEdit_89 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.gridLayout.addWidget(self.lineEdit_89, 9, 6, 1, 1)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.gridLayout.addWidget(self.lineEdit_68, 12, 1, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout.addWidget(self.lineEdit_65, 6, 8, 1, 1)
        self.lineEdit_96 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_96.setObjectName("lineEdit_96")
        self.gridLayout.addWidget(self.lineEdit_96, 8, 5, 1, 1)
        self.lineEdit_87 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.gridLayout.addWidget(self.lineEdit_87, 9, 4, 1, 1)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.gridLayout.addWidget(self.lineEdit_69, 12, 2, 1, 1)
        self.lineEdit_91 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.gridLayout.addWidget(self.lineEdit_91, 9, 8, 1, 1)
        self.lineEdit_85 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.gridLayout.addWidget(self.lineEdit_85, 9, 2, 1, 1)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.gridLayout.addWidget(self.lineEdit_76, 10, 1, 1, 1)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.gridLayout.addWidget(self.lineEdit_74, 12, 7, 1, 1)
        self.lineEdit_86 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.gridLayout.addWidget(self.lineEdit_86, 9, 3, 1, 1)
        self.lineEdit_88 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.gridLayout.addWidget(self.lineEdit_88, 9, 5, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout.addWidget(self.lineEdit_43, 4, 5, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout.addWidget(self.lineEdit_38, 7, 4, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout.addWidget(self.lineEdit_36, 4, 4, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout.addWidget(self.lineEdit_44, 6, 5, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout.addWidget(self.lineEdit_46, 11, 5, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout.addWidget(self.lineEdit_45, 7, 5, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout.addWidget(self.lineEdit_39, 11, 4, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout.addWidget(self.lineEdit_53, 11, 6, 1, 1)
        self.lineEdit_92 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.gridLayout.addWidget(self.lineEdit_92, 8, 1, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout.addWidget(self.lineEdit_41, 2, 5, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout.addWidget(self.lineEdit_56, 3, 7, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout.addWidget(self.lineEdit_60, 11, 7, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout.addWidget(self.lineEdit_50, 4, 6, 1, 1)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.gridLayout.addWidget(self.lineEdit_67, 11, 8, 1, 1)
        self.lineEdit_77 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.gridLayout.addWidget(self.lineEdit_77, 10, 2, 1, 1)
        self.lineEdit_84 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.gridLayout.addWidget(self.lineEdit_84, 9, 1, 1, 1)
        self.lineEdit_90 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.gridLayout.addWidget(self.lineEdit_90, 9, 7, 1, 1)
        self.lineEdit_98 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.gridLayout.addWidget(self.lineEdit_98, 8, 7, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout.addWidget(self.lineEdit_49, 3, 6, 1, 1)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.gridLayout.addWidget(self.lineEdit_72, 12, 5, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout.addWidget(self.lineEdit_34, 2, 4, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 7, 2, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout.addWidget(self.lineEdit_35, 3, 4, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout.addWidget(self.lineEdit_20, 1, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 7, 1, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout.addWidget(self.lineEdit_31, 7, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 6, 1, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout.addWidget(self.lineEdit_58, 6, 7, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout.addWidget(self.lineEdit_29, 4, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout.addWidget(self.lineEdit_32, 11, 3, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout.addWidget(self.lineEdit_37, 6, 4, 1, 1)
        self.lineEdit_99 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_99.setObjectName("lineEdit_99")
        self.gridLayout.addWidget(self.lineEdit_99, 8, 8, 1, 1)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.gridLayout.addWidget(self.lineEdit_75, 12, 8, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout.addWidget(self.lineEdit_54, 1, 7, 1, 1)
        self.lineEdit_81 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.gridLayout.addWidget(self.lineEdit_81, 10, 6, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout.addWidget(self.lineEdit_30, 6, 3, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout.addWidget(self.lineEdit_52, 7, 6, 1, 1)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.gridLayout.addWidget(self.lineEdit_73, 12, 6, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout.addWidget(self.lineEdit_42, 3, 5, 1, 1)
        self.lineEdit_78 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.gridLayout.addWidget(self.lineEdit_78, 10, 3, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout.addWidget(self.lineEdit_48, 2, 6, 1, 1)
        self.lineEdit_82 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.gridLayout.addWidget(self.lineEdit_82, 10, 7, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout.addWidget(self.lineEdit_25, 11, 2, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 4, 1, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout.addWidget(self.lineEdit_51, 6, 6, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout.addWidget(self.lineEdit_21, 2, 2, 1, 1)
        self.lineEdit_95 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_95.setObjectName("lineEdit_95")
        self.gridLayout.addWidget(self.lineEdit_95, 8, 4, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout.addWidget(self.lineEdit_55, 2, 7, 1, 1)
        self.lineEdit_80 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.gridLayout.addWidget(self.lineEdit_80, 10, 5, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout.addWidget(self.lineEdit_57, 4, 7, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout.addWidget(self.lineEdit_23, 4, 2, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout.addWidget(self.lineEdit_22, 3, 2, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout.addWidget(self.lineEdit_62, 2, 8, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout.addWidget(self.lineEdit_63, 3, 8, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.lineEdit_79 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.gridLayout.addWidget(self.lineEdit_79, 10, 4, 1, 1)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.gridLayout.addWidget(self.lineEdit_70, 12, 3, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout.addWidget(self.lineEdit_33, 1, 4, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 3, 1, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout.addWidget(self.lineEdit_47, 1, 6, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout.addWidget(self.lineEdit_24, 6, 2, 1, 1)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout.addWidget(self.lineEdit_66, 7, 8, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout.addWidget(self.lineEdit_40, 1, 5, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout.addWidget(self.lineEdit_61, 1, 8, 1, 1)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.gridLayout.addWidget(self.lineEdit_71, 12, 4, 1, 1)
        self.lineEdit_94 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.gridLayout.addWidget(self.lineEdit_94, 8, 3, 1, 1)
        self.lineEdit_97 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_97.setObjectName("lineEdit_97")
        self.gridLayout.addWidget(self.lineEdit_97, 8, 6, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 0, 7, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 0, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 0, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 4, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 0, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 0, 8, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 6, 1, 1)
        self.lineEdit_100 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.gridLayout.addWidget(self.lineEdit_100, 5, 1, 1, 1)
        self.lineEdit_101 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_101.setObjectName("lineEdit_101")
        self.gridLayout.addWidget(self.lineEdit_101, 5, 2, 1, 1)
        self.lineEdit_102 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.gridLayout.addWidget(self.lineEdit_102, 5, 3, 1, 1)
        self.lineEdit_103 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_103.setObjectName("lineEdit_103")
        self.gridLayout.addWidget(self.lineEdit_103, 5, 4, 1, 1)
        self.lineEdit_104 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_104.setObjectName("lineEdit_104")
        self.gridLayout.addWidget(self.lineEdit_104, 5, 5, 1, 1)
        self.lineEdit_105 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_105.setObjectName("lineEdit_105")
        self.gridLayout.addWidget(self.lineEdit_105, 5, 6, 1, 1)
        self.lineEdit_106 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_106.setObjectName("lineEdit_106")
        self.gridLayout.addWidget(self.lineEdit_106, 5, 7, 1, 1)
        self.lineEdit_107 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_107.setObjectName("lineEdit_107")
        self.gridLayout.addWidget(self.lineEdit_107, 5, 8, 1, 1)
        self.lineEdit_108 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_108.setObjectName("lineEdit_108")
        self.gridLayout.addWidget(self.lineEdit_108, 13, 1, 1, 1)
        self.lineEdit_109 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_109.setObjectName("lineEdit_109")
        self.gridLayout.addWidget(self.lineEdit_109, 13, 2, 1, 1)
        self.lineEdit_110 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_110.setObjectName("lineEdit_110")
        self.gridLayout.addWidget(self.lineEdit_110, 13, 3, 1, 1)
        self.lineEdit_111 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_111.setObjectName("lineEdit_111")
        self.gridLayout.addWidget(self.lineEdit_111, 13, 4, 1, 1)
        self.lineEdit_112 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_112.setObjectName("lineEdit_112")
        self.gridLayout.addWidget(self.lineEdit_112, 13, 5, 1, 1)
        self.lineEdit_113 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_113.setObjectName("lineEdit_113")
        self.gridLayout.addWidget(self.lineEdit_113, 13, 6, 1, 1)
        self.lineEdit_114 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_114.setObjectName("lineEdit_114")
        self.gridLayout.addWidget(self.lineEdit_114, 13, 7, 1, 1)
        self.lineEdit_115 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_115.setObjectName("lineEdit_115")
        self.gridLayout.addWidget(self.lineEdit_115, 13, 8, 1, 1)
        self.lineEdit_116 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_116.setObjectName("lineEdit_116")
        self.gridLayout.addWidget(self.lineEdit_116, 13, 1, 1, 1)
        self.lineEdit_117 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_117.setObjectName("lineEdit_117")
        self.gridLayout.addWidget(self.lineEdit_117, 13, 2, 1, 1)
        self.lineEdit_118 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_118.setObjectName("lineEdit_118")
        self.gridLayout.addWidget(self.lineEdit_118, 13, 3, 1, 1)
        self.lineEdit_119 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_119.setObjectName("lineEdit_119")
        self.gridLayout.addWidget(self.lineEdit_119, 13, 4, 1, 1)
        self.lineEdit_120 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_120.setObjectName("lineEdit_120")
        self.gridLayout.addWidget(self.lineEdit_120, 13, 5, 1, 1)
        self.lineEdit_121 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_121.setObjectName("lineEdit_121")
        self.gridLayout.addWidget(self.lineEdit_121, 13, 6, 1, 1)
        self.lineEdit_122 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_122.setObjectName("lineEdit_122")
        self.gridLayout.addWidget(self.lineEdit_122, 13, 7, 1, 1)
        self.lineEdit_123 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_123.setObjectName("lineEdit_123")
        self.gridLayout.addWidget(self.lineEdit_123, 13, 8, 1, 1)
        
        #date time boxes
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 0, 0, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 1, 0, 1, 1)
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.gridLayout.addWidget(self.dateTimeEdit_4, 2, 0, 1, 1)
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.gridLayout.addWidget(self.dateTimeEdit_3, 3, 0, 1, 1)
        self.dateTimeEdit_6 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_6.setObjectName("dateTimeEdit_6")
        self.gridLayout.addWidget(self.dateTimeEdit_6, 4, 0, 1, 1)
        self.dateTimeEdit_11 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_11.setObjectName("dateTimeEdit_11")
        self.gridLayout.addWidget(self.dateTimeEdit_11, 5, 0, 1, 1)
        self.dateTimeEdit_5 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_5.setObjectName("dateTimeEdit_5")
        self.gridLayout.addWidget(self.dateTimeEdit_5, 6, 0, 1, 1)
        self.dateTimeEdit_13 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_13.setObjectName("dateTimeEdit_13")
        self.gridLayout.addWidget(self.dateTimeEdit_13, 7, 0, 1, 1)
        self.dateTimeEdit_10 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_10.setObjectName("dateTimeEdit_10")
        self.gridLayout.addWidget(self.dateTimeEdit_10, 8, 0, 1, 1)
        self.dateTimeEdit_9 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_9.setObjectName("dateTimeEdit_9")
        self.gridLayout.addWidget(self.dateTimeEdit_9, 9, 0, 1, 1)
        self.dateTimeEdit_8 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_8.setObjectName("dateTimeEdit_8")
        self.gridLayout.addWidget(self.dateTimeEdit_8, 10, 0, 1, 1)
        self.dateTimeEdit_14 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_14.setObjectName("dateTimeEdit_14")
        self.gridLayout.addWidget(self.dateTimeEdit_14, 11, 0, 1, 1)
        self.dateTimeEdit_7 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_7.setObjectName("dateTimeEdit_7")
        self.gridLayout.addWidget(self.dateTimeEdit_7, 12, 0, 1, 1)
        self.dateTimeEdit_15 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_15.setObjectName("dateTimeEdit_15")
        self.gridLayout.addWidget(self.dateTimeEdit_15, 13, 0, 1, 1)
        
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        
        #set point controls
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(910, 40, 139, 541))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.setpoint_grid_layout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.setpoint_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.setpoint_grid_layout.setObjectName("setpoint_grid_layout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setpoint_grid_layout.addItem(spacerItem5, 12, 0, 1, 1)
        self.O2_flow = QtWidgets.QLabel(self.formLayoutWidget)
        self.O2_flow.setObjectName("O2_flow")
        self.setpoint_grid_layout.addWidget(self.O2_flow, 13, 0, 1, 1)
        self.feedpump_control = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.feedpump_control.setObjectName("feedpump_control")
        self.setpoint_grid_layout.addWidget(self.feedpump_control, 8, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setpoint_grid_layout.addItem(spacerItem6, 5, 0, 1, 1)
        self.airflow_control = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.airflow_control.setObjectName("airflow_control")
        self.setpoint_grid_layout.addWidget(self.airflow_control, 18, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setpoint_grid_layout.addItem(spacerItem7, 16, 0, 1, 1)
        self.airflow_num = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.airflow_num.setStyleSheet("QLCDNumber{\n"
"    background-color: rgb(96, 95, 97);\n"
"}")
        self.airflow_num.setObjectName("airflow_num")
        self.setpoint_grid_layout.addWidget(self.airflow_num, 19, 0, 1, 1)
        self.feed_pump = QtWidgets.QPushButton(self.formLayoutWidget)
        self.feed_pump.setObjectName("feed_pump")
        self.setpoint_grid_layout.addWidget(self.feed_pump, 6, 0, 1, 1)
        self.Mode = QtWidgets.QLabel(self.formLayoutWidget)
        self.Mode.setObjectName("Mode")
        self.setpoint_grid_layout.addWidget(self.Mode, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Temperature = QtWidgets.QLabel(self.formLayoutWidget)
        self.Temperature.setObjectName("Temperature")
        self.setpoint_grid_layout.addWidget(self.Temperature, 10, 0, 1, 1)
        self.Airflow = QtWidgets.QLabel(self.formLayoutWidget)
        self.Airflow.setObjectName("Airflow")
        self.setpoint_grid_layout.addWidget(self.Airflow, 17, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.O2flow_control = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.O2flow_control.setObjectName("O2flow_control")
        self.setpoint_grid_layout.addWidget(self.O2flow_control, 14, 0, 1, 1)
        self.O2flow_num = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.O2flow_num.setStyleSheet("QLCDNumber{\n"
"    background-color: rgb(96, 95, 97);\n"
"}")
        self.O2flow_num.setObjectName("O2flow_num")
        self.setpoint_grid_layout.addWidget(self.O2flow_num, 15, 0, 1, 1)
        self.mode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.setpoint_grid_layout.addWidget(self.mode, 3, 0, 1, 1)
        self.temperature_control = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.temperature_control.setObjectName("temperature_control")
        self.setpoint_grid_layout.addWidget(self.temperature_control, 11, 0, 1, 1)
        self.feed_pump_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.feed_pump_2.setObjectName("feed_pump_2")
        self.setpoint_grid_layout.addWidget(self.feed_pump_2, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setpoint_grid_layout.addItem(spacerItem8, 9, 0, 1, 1)
        self.run = QtWidgets.QPushButton(self.formLayoutWidget)
        self.run.setObjectName("run")
        self.setpoint_grid_layout.addWidget(self.run, 4, 0, 1, 1)
        
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1155, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuManual_Log = QtWidgets.QMenu(self.menuBar)
        self.menuManual_Log.setObjectName("menuManual_Log")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuManual_Log.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Cellexus_Cellmaker", "Cellexus_Cellmaker"))
        self.do2.setText(_translate("Cellexus_Cellmaker", "dO2"))
        self.test.setText(_translate("Cellexus_Cellmaker", "Test"))
        self.temperature.setText(_translate("Cellexus_Cellmaker", "Temperature"))
        self.pH.setText(_translate("Cellexus_Cellmaker", "pH"))
        self.co2flow.setText(_translate("Cellexus_Cellmaker", "CO2 Flow"))
        self.pressure.setText(_translate("Cellexus_Cellmaker", "Pressure"))
        self.date.setText(_translate("Cellexus_Cellmaker", "Date"))
        self.motor.setText(_translate("Cellexus_Cellmaker", "Motor"))
        self.o2flow.setText(_translate("Cellexus_Cellmaker", "O2 Flow"))
        self.group.setText(_translate("Cellexus_Cellmaker", "Group"))
        self.datetime.setText(_translate("Cellexus_Cellmaker", "Date/Time"))
        self.airflow.setText(_translate("Cellexus_Cellmaker", "Air Flow"))
        self.operator_2.setText(_translate("Cellexus_Cellmaker", "Operator"))
        self.filename.setText(_translate("Cellexus_Cellmaker", "Manual Log"))
        self.log.setText(_translate("Cellexus_Cellmaker", "Log"))
        self.file_name.setText(_translate("Cellexus_Cellmaker", "Manual Log File Name "))
        self.interval.setText(_translate("Cellexus_Cellmaker", "Interval (s)"))
        self.O2_flow.setText(_translate("Cellexus_Cellmaker", "O2 Flow (lpm) SP"))
        self.feed_pump.setText(_translate("Cellexus_Cellmaker", "Feed Pump ON"))
        self.Mode.setText(_translate("Cellexus_Cellmaker", "Mode"))
        self.Temperature.setText(_translate("Cellexus_Cellmaker", "Temperature (ºC) SP"))
        self.Airflow.setText(_translate("Cellexus_Cellmaker", "Air Flow (lpm) SP"))
        self.mode.setItemText(0, _translate("Cellexus_Cellmaker", "Setpoint"))
        self.mode.setItemText(1, _translate("Cellexus_Cellmaker", "Recipe"))
        self.feed_pump_2.setText(_translate("Cellexus_Cellmaker", "Feed Pump RPM"))
        self.run.setText(_translate("Cellexus_Cellmaker", "RUN"))
        self.openFileButton.setText(_translate("Cellexus_Cellmaker", "Open file"))
        self.menuManual_Log.setTitle(_translate("Cellexus_Cellmaker", "Manual Log"))

    def browsefiles(self):
            fname = QFileDialog.getOpenFileName(self, 'Open File', 'D:\Documents')
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

